# Generated by Django 2.0.6 on 2018-06-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='competitions',
            field=models.ManyToManyField(blank=True, related_name='competitions', to='main.Competition'),
        ),
    ]
